(function (global) {
  'use strict';
  function escapeDiary(value) { return String(value || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
  function renderEntryCard(entry, alters) {
    const alter = alters.find(a => a.id === entry.alterId), mood = getMoods().find(m => m.id === entry.mood), own = entry.alterId === activeAlter.id, readable = !entry.isPrivate || own, editable = own || entry.isSystem;
    const date = new Date(entry.ts).toLocaleString(document.documentElement.lang === 'es' ? 'es-ES' : 'en-GB', { weekday:'short', day:'numeric', month:'short', hour:'2-digit', minute:'2-digit' });
    const ownerNames = (entry.ownerIds || []).map(id => alters.find(a => a.id === id)?.name || '?').join(', ');
    return `<div class="entry-card${entry.isSystem ? ' entry-system' : ''}" data-eid="${entry.id}"><div class="entry-card-top"><div class="entry-alter-avatar" style="background:${alter?.bg || 'var(--bg-2)'};border-color:${alter?.color || 'transparent'}">${alter?.emoji || '◎'}</div><div class="entry-meta"><div class="entry-meta-row"><span class="entry-alter-name" style="color:${alter?.color || 'var(--accent)'}">${escapeDiary(alter?.name || '?')}</span><span class="entry-date">${date}</span>${entry.isPrivate ? '<span class="entry-private-badge">🔒 Private</span>' : ''}${entry.shareOnline && !entry.isPrivate ? '<span class="entry-private-badge" style="background:rgba(138,255,224,.12);color:var(--accent)">Online</span>' : ''}${entry.isSystem ? '<span class="entry-private-badge" style="background:rgba(138,200,255,.15);color:#8ac8ff">📋 System</span>' : ''}${(entry.ownerIds || []).length ? `<span class="entry-owner-badge" title="${escapeDiary(ownerNames)}">◈ ${(entry.ownerIds || []).map(id => alters.find(a => a.id === id)?.emoji || '?').join('')}</span>` : ''}</div>${entry.title ? `<div class="entry-title">${escapeDiary(entry.title)}</div>` : ''}</div>${mood ? `<div class="entry-mood" title="${escapeDiary(mood.label)}">${mood.emoji}</div>` : ''}</div>${readable && entry.body ? `<div class="entry-body">${global.AtriaSafeMarkdown.render(entry.body)}</div>` : !readable ? `<div class="entry-body" style="color:var(--text-3);font-style:italic">${document.documentElement.lang === 'es' ? 'Entrada privada de' : 'Private entry from'} ${escapeDiary(alter?.name || (document.documentElement.lang === 'es' ? 'este alter' : 'this alter'))}</div>` : ''}${(entry.tags?.length || readable) ? `<div class="entry-footer">${(entry.tags || []).map(tag => `<span class="entry-tag">#${escapeDiary(tag)}</span>`).join('')}${readable ? `<div class="entry-actions">${editable ? `<button class="icon-btn btn-edit-entry" data-eid="${entry.id}" title="Edit">✎</button><button class="icon-btn btn-del-entry" data-eid="${entry.id}" title="Delete">✕</button>` : ''}</div>` : ''}</div>` : ''}</div>`;
  }
  function render() {
    if (diarioMode === 'write') return renderDiarioEditor(document.getElementById('app'));
    if (diarioMode === 'detail') return renderDiarioDetail(document.getElementById('app'));
    const es = document.documentElement.lang === 'es', app = document.getElementById('app'), alters = getAlters(), entries = getVisibleEntries(), tags = [...new Set(entries.flatMap(e => e.tags || []))].sort();
    const filtered = entries.filter(e => (diarioFilter.alterId === 'all' || e.alterId === diarioFilter.alterId) && (!diarioFilter.mood || e.mood === diarioFilter.mood) && (!diarioFilter.ownedByMe || !(e.ownerIds || []).length || (e.ownerIds || []).includes(activeAlter.id))).sort((a,b) => b.ts - a.ts);
    const count = {}; entries.forEach(e => { count[e.alterId] = (count[e.alterId] || 0) + 1; });
    const months = {}; filtered.forEach(e => { const d = new Date(e.ts), key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`; (months[key] || (months[key] = [])).push(e); });
    const copy = es ? { title:'Diario', sub:'entrada', all:'Todos', mood:'Estado emocional', memory:'Memoria', mine:'Mis recuerdos', add:'+ Nueva entrada', first:'Escribir primera entrada', empty:'El diario está vacío', filtered:'Sin entradas con estos filtros', alter:'Alter', close:'', edit:'Editar', del:'Eliminar' } : { title:'Journal', sub:'entry', all:'All', mood:'Mood', memory:'Memory', mine:'My memories', add:'+ New entry', first:'Write first entry', empty:'Journal is empty', filtered:'No entries match these filters', alter:'Alter', close:'', edit:'Edit', del:'Delete' };
    app.innerHTML = `<div class="diario-view"><div style="display:flex;align-items:center;justify-content:space-between"><div><div class="fin-title">◫ ${copy.title}</div><div class="fin-subtitle">${entries.length} ${copy.sub}${entries.length !== 1 ? 's' : ''} · ${filtered.length} visible${filtered.length !== 1 ? 's' : ''}</div></div><button class="btn btn-primary" id="btn-new-entry">${copy.add}</button></div><div class="diario-layout"><div class="diario-filters"><div><div class="diario-filter-title">${copy.alter}</div><div class="diario-alter-filter"><div class="diario-alter-opt${diarioFilter.alterId === 'all' ? ' active' : ''}" data-alter="all"><div class="diario-alter-dot" style="background:var(--text-2)"></div><div class="diario-alter-name">${copy.all}</div><div class="diario-alter-count">${entries.length}</div></div>${alters.map(a => `<div class="diario-alter-opt${diarioFilter.alterId === a.id ? ' active' : ''}" data-alter="${a.id}"><div style="font-size:14px">${a.emoji}</div><div class="diario-alter-name">${esc(a.name)}</div><div class="diario-alter-count">${count[a.id] || 0}</div></div>`).join('')}</div></div><div><div class="diario-filter-title">${copy.mood}</div><div class="diario-mood-filter"><div class="mood-filter-chip${!diarioFilter.mood ? ' active' : ''}" data-mood="">${copy.all}</div>${getMoods().filter(m => entries.some(e => e.mood === m.id)).map(m => `<div class="mood-filter-chip${diarioFilter.mood === m.id ? ' active' : ''}" data-mood="${m.id}" title="${esc(m.label)}">${m.emoji}</div>`).join('')}</div></div><div><div class="diario-filter-title">${copy.memory}</div><div class="diario-alter-opt${diarioFilter.ownedByMe ? ' active' : ''}" id="filter-owned-by-me" style="cursor:pointer"><div style="font-size:14px">◈</div><div class="diario-alter-name">${copy.mine}</div></div></div><button class="btn btn-ghost btn-sm" id="btn-new-entry-2" style="width:100%">${copy.add}</button></div><div class="diario-timeline">${Object.keys(months).length ? Object.entries(months).sort((a,b) => b[0].localeCompare(a[0])).map(([key, rows]) => { const [year, month] = key.split('-'), label = new Date(+year, +month - 1, 1).toLocaleString(es ? 'es-ES' : 'en-GB', { month:'long', year:'numeric' }); return `<div class="diario-month-group"><div class="diario-month-label"><span style="text-transform:capitalize">${label}</span><span>${rows.length} ${copy.sub}${rows.length !== 1 ? 's' : ''}</span></div>${rows.map(e => renderEntryCard(e, alters)).join('')}</div>`; }).join('') : `<div class="empty-state" style="padding:60px 20px"><div class="empty-icon">◫</div><div>${filtered.length && entries.length ? copy.filtered : copy.empty}</div><button class="btn btn-primary" style="margin-top:8px" id="btn-new-entry-3">${copy.first}</button></div>`}</div></div></div>`;
    app.querySelectorAll('[data-alter]').forEach(el => el.addEventListener('click', () => { diarioFilter.alterId = el.dataset.alter; render(); }));
    app.querySelectorAll('[data-mood]').forEach(el => el.addEventListener('click', () => { diarioFilter.mood = el.dataset.mood || null; render(); }));
    app.querySelector('#filter-owned-by-me')?.addEventListener('click', () => { diarioFilter.ownedByMe = !diarioFilter.ownedByMe; render(); });
    app.querySelectorAll('#btn-new-entry,#btn-new-entry-2,#btn-new-entry-3').forEach(button => button?.addEventListener('click', () => { diarioMode = 'write'; diarioEditing = null; editorTags = []; render(); }));
    app.querySelectorAll('.entry-card[data-eid]').forEach(card => card.addEventListener('click', event => { if (event.target.closest('.entry-actions')) return; diarioDetailId = card.dataset.eid; diarioMode = 'detail'; render(); }));
    app.querySelectorAll('.btn-edit-entry').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); const entry = loadEntries().find(x => x.id === button.dataset.eid); if (entry) { diarioEditing = entry; editorTags = [...(entry.tags || [])]; diarioMode = 'write'; render(); } }));
    app.querySelectorAll('.btn-del-entry').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); const all = loadEntries(), entry = all.find(x => x.id === button.dataset.eid); if (!entry) return; saveEntries(all.filter(x => x.id !== entry.id)); render(); softDelete(es ? 'Entrada eliminada' : 'Entry deleted', () => {}, () => { const current = loadEntries(); current.push(entry); saveEntries(current); render(); }); }));
  }
  global.renderEntryCard = renderEntryCard;
  global.escDiary = escapeDiary;
  global.renderDiarioView = render;
  global.AtriaDiaryView = Object.freeze({ render });
})(window);
