(function (global) {
  'use strict';
  function renderEditorTags(app) {
    const row = app.querySelector('#editor-tags-row'); if (!row) return;
    const value = app.querySelector('#tag-input')?.value || '';
    row.innerHTML = `<span style="font-family:'DM Mono',monospace;font-size:10px;color:var(--text-3)">#</span>${editorTags.map((tag, i) => `<span class="tag-pill-rm">${escDiary(tag)}<button data-ti="${i}">✕</button></span>`).join('')}<input class="tag-input" id="tag-input" placeholder="${document.documentElement.lang === 'es' ? 'Añadir etiqueta...' : 'Add tag...'}" value="${escDiary(value)}" autocomplete="off">`;
    row.querySelectorAll('[data-ti]').forEach(button => button.addEventListener('click', () => { editorTags.splice(+button.dataset.ti, 1); renderEditorTags(app); }));
    row.querySelector('#tag-input')?.addEventListener('keydown', event => { if ((event.key === 'Enter' || event.key === ',' || event.key === ' ') && event.target.value.trim()) { event.preventDefault(); const tag = event.target.value.trim().toLowerCase().replace(/[^a-z0-9áéíóúüñ-]/g, ''); if (tag && !editorTags.includes(tag)) editorTags.push(tag); renderEditorTags(app); } if (event.key === 'Backspace' && !event.target.value && editorTags.length) { editorTags.pop(); renderEditorTags(app); } });
  }
  function renderDiarioEditor(app) {
    const es = document.documentElement.lang === 'es', entry = diarioEditing, edit = !!entry, mood = entry?.mood || null;
    const copy = es ? { back:'← Volver', edit:'Editar entrada', create:'Nueva entrada', title:'Título (opcional)...', state:'Estado', note:'Escribe lo que sientes, lo que pasó, lo que piensas...', private:'Privada', system:'Sistema', share:'Compartir online', owners:'◈ Dueños', cancel:'Cancelar', save:'Guardar cambios', publish:'Publicar entrada', empty:'⚠ Escribe algo antes de guardar', updated:'Entrada actualizada ✓', saved:'Entrada guardada ✓' } : { back:'← Back', edit:'Edit entry', create:'New entry', title:'Title (optional)...', state:'Mood', note:'Write what you feel, what happened, what you think...', private:'Private', system:'System', share:'Share online', owners:'◈ Owners', cancel:'Cancel', save:'Save changes', publish:'Publish entry', empty:'⚠ Write something before saving', updated:'Entry updated ✓', saved:'Entry saved ✓' };
    app.innerHTML = `<div class="diario-view"><div style="display:flex;align-items:center;gap:10px"><button class="btn btn-ghost" id="btn-back-list">${copy.back}</button><div class="fin-title" style="font-size:20px">${edit ? copy.edit : copy.create}</div></div><div class="diario-editor"><div class="editor-toolbar"><input class="editor-title-input" id="ed-title" placeholder="${copy.title}" value="${escDiary(entry?.title || '')}"></div><div class="editor-meta-row"><div style="font-family:'DM Mono',monospace;font-size:10px;color:var(--text-2);letter-spacing:.1em;text-transform:uppercase;margin-right:4px">${copy.state}</div><div class="mood-picker" id="mood-picker">${getMoods().map(item => `<div class="mood-opt${mood === item.id ? ' selected' : ''}" data-mood="${item.id}" title="${escDiary(item.label)}">${item.emoji}</div>`).join('')}</div><input type="hidden" id="ed-mood" value="${entry?.mood || ''}"><div style="flex:1"></div><div class="editor-private-toggle${entry?.isPrivate ? ' on' : ''}" id="ed-private"><span>${entry?.isPrivate ? '🔒' : '🔓'}</span><span>${copy.private}</span></div><input type="hidden" id="ed-private-val" value="${entry?.isPrivate ? '1' : ''}"><div class="editor-private-toggle${entry?.isSystem ? ' on' : ''}" id="ed-system" style="margin-left:6px"><span>📋</span><span>${copy.system}</span></div><input type="hidden" id="ed-system-val" value="${entry?.isSystem ? '1' : ''}"><div class="editor-private-toggle${entry?.shareOnline && !entry?.isPrivate ? ' on' : ''}" id="ed-share-online" style="margin-left:6px"><span>◎</span><span>${copy.share}</span></div><input type="hidden" id="ed-share-online-val" value="${entry?.shareOnline && !entry?.isPrivate ? '1' : ''}"></div><div class="editor-owners-row"><span class="editor-owners-label">${copy.owners}</span><div class="ed-owners-chips" id="ed-owners-chips">${getAlters().map(a => `<div class="ed-owner-chip${(entry?.ownerIds || []).includes(a.id) ? ' on' : ''}" data-aid="${a.id}" style="--oc:${a.color}">${a.emoji || '●'} ${escDiary(a.name)}</div>`).join('')}</div><input type="hidden" id="ed-owners-data" value="${escDiary(JSON.stringify(entry?.ownerIds || []))}"></div><div class="editor-body"><textarea class="editor-textarea" id="ed-body" placeholder="${copy.note}">${escDiary(entry?.body || '')}</textarea></div><div class="editor-tags-row" id="editor-tags-row"></div><div class="editor-footer"><button class="btn btn-ghost" id="btn-cancel-edit">${copy.cancel}</button><button class="btn btn-primary" id="btn-save-entry">${edit ? copy.save : copy.publish}</button></div></div></div>`;
    const body = app.querySelector('#ed-body');
    if (body) {
      const preview = document.createElement('div');
      preview.className = 'diary-markdown-preview';
      preview.innerHTML = `<div class="diary-markdown-preview-label">${es ? 'Vista previa segura' : 'Safe preview'}</div><div class="diary-markdown-preview-content"></div>`;
      body.parentElement.appendChild(preview);
      const updatePreview = () => { preview.querySelector('.diary-markdown-preview-content').innerHTML = global.AtriaSafeMarkdown.render(body.value) || `<span style="color:var(--text-3)">${es ? 'La vista previa aparecerá aquí.' : 'Preview will appear here.'}</span>`; };
      body.addEventListener('input', updatePreview);
      updatePreview();
    }
    renderEditorTags(app);
    app.querySelectorAll('.mood-opt').forEach(option => option.addEventListener('click', () => { app.querySelectorAll('.mood-opt').forEach(item => item.classList.remove('selected')); option.classList.add('selected'); app.querySelector('#ed-mood').value = option.dataset.mood; }));
    app.querySelector('#ed-private')?.addEventListener('click', () => { const value = app.querySelector('#ed-private-val'), on = value.value === '1'; value.value = on ? '' : '1'; app.querySelector('#ed-private').classList.toggle('on', !on); app.querySelector('#ed-private span:first-child').textContent = on ? '🔓' : '🔒'; if (!on) { app.querySelector('#ed-share-online-val').value = ''; app.querySelector('#ed-share-online')?.classList.remove('on'); } });
    app.querySelector('#ed-system')?.addEventListener('click', () => { const value = app.querySelector('#ed-system-val'), on = value.value === '1'; value.value = on ? '' : '1'; app.querySelector('#ed-system').classList.toggle('on', !on); if (!on) { app.querySelector('#ed-private-val').value = ''; app.querySelector('#ed-private').classList.remove('on'); app.querySelector('#ed-private span:first-child').textContent = '🔓'; } });
    app.querySelector('#ed-share-online')?.addEventListener('click', () => { if (app.querySelector('#ed-private-val').value === '1') return showToast(es ? 'Las entradas privadas no se pueden compartir online' : 'Private entries cannot be shared online'); const value = app.querySelector('#ed-share-online-val'), on = value.value === '1'; value.value = on ? '' : '1'; app.querySelector('#ed-share-online').classList.toggle('on', !on); });
    app.querySelectorAll('.ed-owner-chip').forEach(chip => chip.addEventListener('click', () => { chip.classList.toggle('on'); app.querySelector('#ed-owners-data').value = JSON.stringify([...app.querySelectorAll('.ed-owner-chip.on')].map(item => item.dataset.aid)); }));
    app.querySelector('#btn-back-list')?.addEventListener('click', () => { diarioMode = 'list'; diarioEditing = null; editorTags = []; renderDiario(); });
    app.querySelector('#btn-cancel-edit')?.addEventListener('click', () => { diarioMode = 'list'; diarioEditing = null; editorTags = []; renderDiario(); });
    app.querySelector('#btn-save-entry')?.addEventListener('click', () => { const title = app.querySelector('#ed-title').value.trim(), body = app.querySelector('#ed-body').value.trim(); if (!body) return showToast(copy.empty); const privateEntry = app.querySelector('#ed-private-val').value === '1', system = app.querySelector('#ed-system-val').value === '1', ownerIds = JSON.parse(app.querySelector('#ed-owners-data').value || '[]'), item = { id:entry?.id || uid(), alterId:activeAlter.id, ts:entry?.ts || Date.now(), editedTs:edit ? Date.now() : undefined, title, body, mood:app.querySelector('#ed-mood').value || null, isPrivate:system ? false : privateEntry, isSystem:system || undefined, ownerIds, shareOnline:(!privateEntry && app.querySelector('#ed-share-online-val').value === '1') || undefined, tags:[...editorTags] }; let list = loadEntries(); if (edit) list = list.map(x => x.id === entry.id ? item : x); else list.push(item); saveEntries(list); showToast(edit ? copy.updated : copy.saved); diarioMode = 'list'; diarioEditing = null; editorTags = []; renderDiario(); });
  }
  global.renderDiarioEditor = renderDiarioEditor;
  global.renderEditorTags = renderEditorTags;
})(window);
