(function (global) {
  'use strict';
  function renderDiarioDetail(app) {
    const es = document.documentElement.lang === 'es', entry = getVisibleEntries().find(item => item.id === diarioDetailId);
    if (!entry) { diarioMode = 'list'; return renderDiario(); }
    const alter = getAlters().find(a => a.id === entry.alterId), mood = getMoods().find(m => m.id === entry.mood), date = new Date(entry.ts).toLocaleString(es ? 'es-ES' : 'en-GB', { weekday:'long', day:'numeric', month:'long', year:'numeric', hour:'2-digit', minute:'2-digit' }), canEdit = entry.alterId === activeAlter.id;
    const copy = es ? { back:'← Volver al diario', private:'Privado', edited:'editado', edit:'Editar', del:'Eliminar', archive:'↓ Archivar entrada', archived:'Entrada archivada', deleted:'Entrada eliminada', confirm:'¿Eliminar esta entrada?' } : { back:'← Back to journal', private:'Private', edited:'edited', edit:'Edit', del:'Delete', archive:'↓ Archive entry', archived:'Entry archived', deleted:'Entry deleted', confirm:'Delete this entry?' };
    app.innerHTML = `<div class="diario-view"><button class="btn btn-ghost" id="btn-back-detail" style="align-self:flex-start">${copy.back}</button><div class="entry-detail"><div class="entry-detail-header"><div style="display:flex;align-items:flex-start;gap:12px"><div class="entry-alter-avatar" style="width:40px;height:40px;font-size:20px;background:${alter?.bg || 'var(--bg-2)'};border:1.5px solid ${alter?.color || 'transparent'}">${alter?.emoji || '◎'}</div><div style="flex:1"><div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap"><span style="font-size:13px;font-weight:700;color:${alter?.color || 'var(--accent)'}">${escDiary(alter?.name || '?')}</span><span style="font-family:'DM Mono',monospace;font-size:10px;color:var(--text-2)">${date}</span>${entry.isPrivate ? `<span class="entry-private-badge">🔒 ${copy.private}</span>` : ''}${entry.shareOnline && !entry.isPrivate ? '<span class="entry-private-badge" style="background:rgba(138,255,224,.12);color:var(--accent)">Online</span>' : ''}${entry.editedTs ? `<span style="font-family:'DM Mono',monospace;font-size:9px;color:var(--text-3)">${copy.edited}</span>` : ''}</div>${entry.title ? `<div style="font-size:20px;font-weight:800;letter-spacing:-.02em;margin-top:8px">${escDiary(entry.title)}</div>` : ''}</div>${mood ? `<div style="font-size:28px" title="${escDiary(mood.label)}">${mood.emoji}</div>` : ''}</div></div><div class="entry-detail-body">${global.AtriaSafeMarkdown.render(entry.body)}</div>${entry.tags?.length ? `<div class="entry-detail-footer">${entry.tags.map(tag => `<span class="entry-tag">#${escDiary(tag)}</span>`).join('')}</div>` : ''}</div>${canEdit ? `<div style="display:flex;gap:8px"><button class="btn btn-ghost" id="btn-edit-detail">✎ ${copy.edit}</button><button class="btn btn-danger" id="btn-del-detail">✕ ${copy.del}</button>${!entry.isArchived ? `<button class="btn btn-ghost" id="btn-archive-entry">${copy.archive}</button>` : ''}</div>` : ''}</div>`;
    app.querySelector('#btn-back-detail')?.addEventListener('click', () => { diarioMode = 'list'; renderDiario(); });
    app.querySelector('#btn-edit-detail')?.addEventListener('click', () => { diarioEditing = entry; editorTags = [...(entry.tags || [])]; diarioMode = 'write'; renderDiario(); });
    app.querySelector('#btn-del-detail')?.addEventListener('click', () => { const all = loadEntries(), saved = all.find(item => item.id === entry.id); if (!saved || !confirm(copy.confirm)) return; saveEntries(all.filter(item => item.id !== entry.id)); diarioMode = 'list'; renderDiario(); softDelete(copy.deleted, () => {}, () => { const current = loadEntries(); current.push(saved); saveEntries(current); renderDiario(); }); });
    app.querySelector('#btn-archive-entry')?.addEventListener('click', () => { const all = loadEntries(), current = all.find(item => item.id === entry.id); if (current) { current.isArchived = true; saveEntries(all); showToast(copy.archived); diarioMode = 'list'; renderDiario(); } });
  }
  global.renderDiarioDetail = renderDiarioDetail;
})(window);
