(function (global) {
  'use strict';
  function openNotaModal(nota) {
    const es = document.documentElement.lang === 'es';
    const edit = !!nota;
    const n = nota || { title:'', body:'', color:'neutral', tags:[], isPrivate:false, pinned:false, alterId:activeAlter.id };
    let tags = [...(n.tags || [])];
    const copy = es ? { edit:'Editar nota', create:'Nueva nota', title:'Título (opcional)', titlePh:'Título de la nota...', body:'Contenido', bodyPh:'Escribe tu nota...', color:'Color', tags:'Etiquetas', private:'Privada', privateSub:'Solo visible para ti', pin:'📌 Fijar', pinSub:'Aparece siempre arriba', cancel:'Cancelar', save:'Guardar', add:'Crear nota', empty:'⚠ Escribe algo', updated:'Nota actualizada ✓', created:'Nota creada ✓' } : { edit:'Edit note', create:'New note', title:'Title (optional)', titlePh:'Note title...', body:'Content', bodyPh:'Write your note...', color:'Color', tags:'Tags', private:'Private', privateSub:'Only visible to you', pin:'📌 Pin', pinSub:'Always appears first', cancel:'Cancel', save:'Save', add:'Create note', empty:'⚠ Write something', updated:'Note updated ✓', created:'Note created ✓' };
    const tagMarkup = () => `${tags.map((tag, i) => `<span class="tag-pill-rm">${escN(tag)}<button data-ti="${i}">✕</button></span>`).join('')}<input class="tag-input" id="nt-tag-input" placeholder="tag..." autocomplete="off" style="flex:1;min-width:60px">`;
    openModal(`<div class="modal-title">${edit ? copy.edit : copy.create}</div><div class="form-grid"><div class="form-row"><div class="form-label">${copy.title}</div><input type="text" id="nt-title" placeholder="${copy.titlePh}" value="${escN(n.title || '')}"></div><div class="form-row"><div class="form-label">${copy.body}</div><textarea id="nt-body" placeholder="${copy.bodyPh}" style="min-height:140px">${escN(n.body || '')}</textarea></div><div class="form-row"><div class="form-label">${copy.color}</div><div class="nota-color-grid">${NOTA_COLORS.map(color => `<div class="nota-color-swatch${n.color === color.id ? ' selected' : ''}" data-nc="${color.id}" style="background:${color.hex};border-color:${n.color === color.id ? color.text : 'transparent'};box-shadow:inset 0 0 0 1px ${color.border}"></div>`).join('')}</div><input type="hidden" id="nt-color" value="${n.color || 'neutral'}"></div><div class="form-row"><div class="form-label">${copy.tags}</div><div id="nt-tags-row" style="display:flex;align-items:center;gap:6px;flex-wrap:wrap;padding:8px 10px;background:var(--bg-2);border:1px solid var(--border);border-radius:8px"><span style="font-family:'DM Mono',monospace;font-size:10px;color:var(--text-3)">#</span>${tagMarkup()}</div></div><div style="display:flex;gap:16px"><div class="form-row" style="flex-direction:row;align-items:center;gap:10px;flex:1"><div class="toggle-switch${n.isPrivate ? ' on' : ''}" id="nt-private"></div><div><div class="perm-toggle-label">${copy.private}</div><div class="perm-toggle-sublabel">${copy.privateSub}</div></div></div><div class="form-row" style="flex-direction:row;align-items:center;gap:10px;flex:1"><div class="toggle-switch${n.pinned ? ' on' : ''}" id="nt-pinned"></div><div><div class="perm-toggle-label">${copy.pin}</div><div class="perm-toggle-sublabel">${copy.pinSub}</div></div></div></div></div><div class="modal-footer"><button class="btn btn-ghost" data-cancel>${copy.cancel}</button><button class="btn btn-primary" data-submit>${edit ? copy.save : copy.add}</button></div>`, ov => {
      const title = ov.querySelector('#nt-title').value.trim(), body = ov.querySelector('#nt-body').value.trim();
      if (!body && !title) return showToast(copy.empty);
      const entry = { id:n.id || uid(), alterId:activeAlter.id, title, body, color:ov.querySelector('#nt-color').value, tags:[...tags], isPrivate:ov.querySelector('#nt-private').classList.contains('on'), pinned:ov.querySelector('#nt-pinned').classList.contains('on'), ts:n.ts || Date.now(), editedTs:edit ? Date.now() : undefined };
      let list = loadNotas(); if (edit) list = list.map(item => item.id === n.id ? entry : item); else list.push(entry); saveNotas(list); closeModal(); showToast(edit ? copy.updated : copy.created); renderNotasView();
    });
    const ov = document.querySelector('.modal-overlay');
    ov.querySelectorAll('.nota-color-swatch').forEach(sw => sw.addEventListener('click', () => { ov.querySelectorAll('.nota-color-swatch').forEach(s => { s.classList.remove('selected'); s.style.borderColor = 'transparent'; }); sw.classList.add('selected'); const color = NOTA_COLORS.find(c => c.id === sw.dataset.nc); sw.style.borderColor = color?.text || 'white'; ov.querySelector('#nt-color').value = sw.dataset.nc; }));
    ov.querySelector('#nt-private')?.addEventListener('click', () => ov.querySelector('#nt-private').classList.toggle('on'));
    ov.querySelector('#nt-pinned')?.addEventListener('click', () => ov.querySelector('#nt-pinned').classList.toggle('on'));
    const wireTags = () => { const row = ov.querySelector('#nt-tags-row'); if (!row) return; row.innerHTML = `<span style="font-family:'DM Mono',monospace;font-size:10px;color:var(--text-3)">#</span>${tagMarkup()}`; row.querySelectorAll('[data-ti]').forEach(button => button.addEventListener('click', () => { tags.splice(+button.dataset.ti, 1); wireTags(); })); const input = row.querySelector('#nt-tag-input'); input?.focus(); input?.addEventListener('keydown', event => { if ((event.key === 'Enter' || event.key === ',' || event.key === ' ') && event.target.value.trim()) { event.preventDefault(); const value = event.target.value.trim().toLowerCase().replace(/[^a-z0-9áéíóúüñ-]/g, ''); if (value && !tags.includes(value)) tags.push(value); wireTags(); } if (event.key === 'Backspace' && !event.target.value && tags.length) { tags.pop(); wireTags(); } }); };
    wireTags();
  }
  global.openNotaModal = openNotaModal;
})(window);
